name: deploy-union
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
          
      - name: Build Frontend
        run: |
          npm install
          npm run build

      - name: Copy Build Files to Server Directory
        run: |
          mkdir -p server
          cp -r dist/* server/
          
      - name: Commit and Push to New Repository
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          TARGET_REPO: Shahab987/phonegon-union  # Your target repo
          TARGET_BRANCH: main  # Your target branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --single-branch --branch $TARGET_BRANCH https://x-access-token:${PAT_TOKEN}@github.com/${TARGET_REPO}.git output-repo
          cp -r server/* output-repo/
          cd output-repo
          git add .
          git commit -m "Update built files"
          git push origin $TARGET_BRANCH