name: CD-Liara
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build Frontend
        run: |
          npm install
          npm run build

      - name: Go to Server Directory
        run: cd server

      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          "here i want to go to server dir"
          npm i -g @liara/cli@5
          liara deploy --app="mosaleh-node" --api-token="$LIARA_TOKEN" --no-app-logs --port=3003
